alter session set nls_date_format='YYYY-MM-DD HH24:MI:SS';
alter session set NLS_TIMESTAMP_FORMAT='YYYY-MM-DD HH24:MI:SS.FF3';

set term off
set feed off

@@ topsql_elapse_pe_cdb 
@@ backup_info 
@@ patch_info 
@@ awr_misc_cdb 
@@ topsql_shmemory_cdb 
@@ awr_osstat_cdb 
@@ undo_tablespace_cdb 
@@ controlfile 
@@ redolog 
@@ sched_jobs_cdb 
@@ topsql_exec_cdb 
@@ fileio_cdb 
@@ awr_bgevent_cdb 
@@ topsql_parse_cdb 
@@ parameter_nonum 
@@ pload_cdb 
@@ topsql_cpu_cdb 
@@ topsql_buffgets_cdb 
@@ idle_events
@@ awr_sga_cdb
@@ awr_enq_cdb 
@@ topsql_uiow_pe_cdb 
@@ topsql_rows_pe_cdb 
@@ arl_dest 
@@ tfileio_cdb 
@@ topsql_sorts_pe_cdb 
@@ parameter_num 
@@ topsql_gets_pe_cdb 
@@ topsql_uiow_cdb 
@@ topsql_appw_cdb 
@@ awr_sysstat_cdb 
@@ topsql_elapse_cdb 
@@ topsql_phr_pe_cdb 
@@ topsql_concurw_cdb 
@@ topsql_cluw_cdb 
@@ auto_tasks_cdb 
@@ topsql_sorts_cdb 
@@ topsql_pxexec_cdb 
@@ user_privs_cdb 
@@ topsql_conw_pe_cdb 
@@ tablespace_cdb 
@@ instance 
@@ topsql_invalid_cdb 
@@ topsql_rows_cdb 
@@ expu_cdb 
@@ alert_dest 
@@ awr_event_cdb 
@@ topsql_cpu_pe_cdb 
@@ datafiles 
@@ fra_info 
@@ topsql_parse_pe_cdb 
@@ sessions 
@@ uncommit_tx_cdb 
@@ awr_fileio_cdb 
@@ database 
@@ topsql_cluw_pe_cdb 
@@ awr_tmodel_cdb 
@@ topsql_phr_cdb 
@@ cursor_eff 
@@ sql_summary_cdb 
@@ awr_sql_cdb 
@@ pdb_info_cdb 
@@ memory_info 
@@ temp_tablespace_cdb 
@@ awr_latch_cdb 
@@ topsql_appw_pe_cdb 
